/**
 * Authoring sheet for the MAKE TODAY beat. `npm run make-today -- <n>`.
 *
 * This one cannot be derived, and it is worth being exact about why. Every
 * record has a `quantity` on every ingredient, so the field looks complete —
 * but the values are instructions, not measurements:
 *
 *     banana rhizome  "cut into pieces"
 *     water           "for boiling"
 *     ghee            "to cook"
 *
 * Nobody can cook from that, and the product promises quantities and a time.
 * Generating them would be writing recipes and calling them history, which is
 * the one thing this corpus exists to avoid. So this script does not write the
 * beat. It assembles everything an editor needs to write one — the historical
 * ingredients and method, what displaced what, and the questions that have to
 * be answered — and gets out of the way.
 *
 * Ordered by how little work each record needs: fewest ingredients and steps
 * first, so the easy ones can be cleared quickly and the pattern established
 * before anyone reaches the hard ones.
 */
import { readFile, writeFile } from 'node:fs/promises';
import type { Recipe } from '../lib/types';

interface Displacement {
  id: string;
  traditional: string;
  matches: string[];
  replaced_by: string;
  when: string;
  caution?: string;
}

const limit = Number(process.argv.slice(2).find((a) => /^\d+$/.test(a)) ?? 25);

const recipes = JSON.parse(
  await readFile(new URL('../data/recipes.json', import.meta.url), 'utf8'),
) as Recipe[];
const { displacements } = JSON.parse(
  await readFile(new URL('../data/displacements.json', import.meta.url), 'utf8'),
) as { displacements: Displacement[] };

/** Cheapest first: an editor should get a rhythm going before the hard ones. */
const ordered = [...recipes].sort(
  (a, b) => a.ingredients.length + a.steps.length - (b.ingredients.length + b.steps.length),
);

const lines: string[] = [
  '# MAKE TODAY — authoring sheet',
  '',
  `Generated by \`npm run make-today\`. ${limit} of ${recipes.length} records, easiest first.`,
  '',
  'For each dish, write a version someone can cook this week: real quantities, a',
  'real order, and a time. Keep the traditional ingredient — the point is to cook',
  'the restored version, so ghee rather than vanaspati and gur rather than refined',
  'sugar. Where the historical record gives no amount, choose one that works and',
  'mark it as a modern reconstruction; do not present it as what the text said.',
  '',
  'Leave a dish blank rather than guessing at it. A missing MAKE TODAY is a gap.',
  'An invented one is a claim.',
  '',
  '---',
  '',
];

for (const r of ordered.slice(0, limit)) {
  const ing = r.ingredients.map((i) => (i.modern_name + ' ' + i.original).toLowerCase()).join(' | ');
  const applies = displacements.filter((d) => d.matches.some((m) => ing.includes(m.toLowerCase())));

  lines.push(`### ${r.name.english}  \`${r.id}\``);
  lines.push('');
  lines.push(`**Source** ${r.source.text}, ${r.source.period}`);
  lines.push(`  ${r.source.url}`);
  lines.push('');
  lines.push('**Historical ingredients** — note the quantities are qualitative:');
  for (const i of r.ingredients) {
    lines.push(`  - ${i.modern_name}${i.original && i.original !== i.modern_name ? ` (${i.original})` : ''} — "${i.quantity}"`);
  }
  lines.push('');
  lines.push('**Historical method:**');
  r.steps.forEach((s, n) => lines.push(`  ${n + 1}. ${s}`));
  if (applies.length) {
    lines.push('');
    lines.push('**Keep the traditional side of these:**');
    for (const d of applies) {
      lines.push(`  - ${d.traditional} — not ${d.replaced_by} (${d.when})`);
      if (d.caution) lines.push(`    note: ${d.caution.split('.')[0]}.`);
    }
  }
  lines.push('');
  lines.push('```yaml');
  lines.push('restore_today:');
  lines.push('  time_min:        # total, honestly');
  lines.push('  ingredients:     # kirana-available, with amounts');
  lines.push('    - ');
  lines.push('  steps:           # numbered, cookable without the historical text');
  lines.push('    - ');
  lines.push('```');
  lines.push('');
}

const out = new URL('../data/make-today-sheet.md', import.meta.url);
await writeFile(out, lines.join('\n'), 'utf8');
console.log(`\nWrote data/make-today-sheet.md — ${Math.min(limit, recipes.length)} records`);
console.log('Nothing was generated. Fill the yaml blocks by hand.\n');
process.exit(0);
