/**
 * Generates `src/lib/community/otp-email-images.ts`: the verification email's
 * four images (the Kranti logo and the Instagram/YouTube/X icons) as base64 PNG.
 *
 * They are embedded in the email as inline (CID) attachments rather than hosted
 * and loaded from the site. Hosted images 404 until a deploy, Gmail fetches them
 * through Google's servers so localhost can never serve them, and clients that
 * block remote images hold them back. `data:` URIs are not an option: Gmail
 * strips them. An inline attachment travels inside the message itself.
 *
 * They are PNG because mail clients do not render SVG. The logo is tinted onto
 * a solid cream plate because the site uses `brand/kranti.png` as a mask, so
 * the file itself carries no colour of its own, only an alpha.
 *
 *   npx tsx scripts/make-email-assets.ts
 *
 * One-off: run it again only if the logo or a social SVG changes. It is not
 * part of `npm run check`.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import sharp from "sharp";

const root = process.cwd();
const target = path.join(root, "src", "lib", "community", "otp-email-images.ts");

/* Twice the size `otp-email.ts` shows them at (64 px logo, 28 px icons), so
   they stay sharp on a dense screen; check-otp fails if the two drift apart. */
const LOGO_PX = 128;
const ICON_PX = 56;

type Img = { filename: string; width: number; height: number; content: string };

async function encode(filename: string, pipeline: ReturnType<typeof sharp>): Promise<Img> {
  const { data, info } = await pipeline.toBuffer({ resolveWithObject: true });
  return { filename, width: info.width, height: info.height, content: data.toString("base64") };
}

async function main() {
  const logo = sharp(path.join(root, "public", "brand", "kranti.png")).resize({ width: LOGO_PX });
  const alpha = await logo.clone().extractChannel("alpha").toBuffer();
  const { width = 0, height = 0 } = await sharp(alpha).metadata();

  const images: Record<string, Img> = {
    logo: await encode(
      "kranti-logo.png",
      sharp({ create: { width, height, channels: 3, background: "#f8a81b" } })
        .joinChannel(alpha)
        .png({ compressionLevel: 9 }),
    ),
  };
  for (const n of ["instagram", "youtube", "x"]) {
    images[n] = await encode(
      `social-${n}.png`,
      sharp(path.join(root, "public", "brand", "social", `${n}.svg`), { density: 144 })
        .resize(ICON_PX, ICON_PX)
        .png({ compressionLevel: 9 }),
    );
  }

  const body = Object.entries(images)
    .map(
      ([k, i]) =>
        `  ${k}: { filename: ${JSON.stringify(i.filename)}, width: ${i.width}, height: ${i.height}, content: ${JSON.stringify(i.content)} },`,
    )
    .join("\n");
  writeFileSync(
    target,
    `// Generated by scripts/make-email-assets.ts — do not edit by hand. Re-run that
// script if brand/kranti.png or brand/social/*.svg changes.
//
// The OTP email's images as base64 PNG, so they travel inside the email as
// inline (CID) attachments instead of loading from the site.

export const EMAIL_IMAGES = {
${body}
} as const;
`,
  );
}

main().then(() => process.exit(0));
