/**
 * Review sheet for the queries the vector fallback changes.
 * `npx tsx scripts/review-vector-misses.ts`
 *
 * `tests/retrieval-queries.json` was written against the 31-record corpus, so
 * every `expect: null` means "nothing in those 31 answers this". The index holds
 * 199, and some of those nulls are now wrong: the corpus really does have a
 * jalebi, and a record whose own name says "early puran poli".
 *
 * Turning the fallback on drops the harness from 132/132 to 108/132, and the
 * harness cannot say which of those 24 are real. Two very different things are
 * mixed together:
 *
 *   - a wrong ancestor — "butter chicken" answered with a 12th-century chicken
 *     dish, which is the campaign risk this project exists to prevent
 *   - a stale expectation — "jalebi" answered with the Jalebi record, marked
 *     wrong only because the test predates it
 *
 * Tuning against the file as it stands would teach retrieval to stop finding
 * jalebi in order to score better, which is the same trap the gold set had.
 *
 * So: print each changed case with the record it now returns and the evidence
 * to judge it. Nothing here decides anything — it makes the decision possible.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { fileCorpus, loadCorpus } from "../src/lib/corpus/load";
import { MIN_KEYWORD_SCORE } from "../src/lib/retrieval/retrieve";

interface Case {
  q: string;
  expect: string | null;
}

const cases = (
  JSON.parse(readFileSync(resolve(process.cwd(), "tests/retrieval-queries.json"), "utf8")) as {
    cases: Case[];
  }
).cases;

async function main() {
  const local = loadCorpus();
  const lines: string[] = [];
  let changed = 0;

  for (const c of cases) {
    // Only cases the fallback can affect: the ones that currently decline.
    if (c.expect !== null) continue;

    const keyword = await fileCorpus.searchKeyword(c.q, 3);
    if (keyword.length && keyword[0].score >= MIN_KEYWORD_SCORE) continue;

    const vector = await fileCorpus.searchVectors(c.q, 3);
    if (!vector.length) continue;

    changed++;
    const top = vector[0];
    const r = top.record;

    lines.push(`### "${c.q}"`);
    lines.push("");
    lines.push("- [ ] **keep null** — the fallback is wrong here, retrieval must decline");
    lines.push(`- [ ] **accept ${r.slug}** — this genuinely answers the query`);
    lines.push("");
    lines.push(`  returns: **${r.dish_name_modern}** _(${r.dish_name_source ?? "—"})_  ·  score ${top.score.toFixed(3)}`);
    lines.push(`  source:  ${r.source.text}, ${r.source.century}`);
    lines.push(`  region:  ${r.region ?? "—"}`);
    lines.push(`  ingredients: ${r.ingredients.map((i) => i.name).slice(0, 8).join(", ")}`);
    if (r.contested_points.length) lines.push(`  notes: ${r.contested_points[0]}`);
    lines.push(`  runners-up: ${vector.slice(1).map((v) => v.record.dish_name_modern).join(" · ") || "—"}`);
    lines.push("");
  }

  const header = `# Vector-fallback review

  Generated by \`npx tsx scripts/review-vector-misses.ts\`.

  ${changed} queries currently expect \`null\` but get an answer once
  \`VECTOR_FALLBACK=on\`. Each is one of two things and only a human can say which:

  **A wrong ancestor** — the dish is modern, or the query is not a dish at all, and
  the record returned is a coincidence. These must stay \`null\`. A wrong ancestor
  is worse than no ancestor.

  **A stale expectation** — the test says \`null\` because the 31-record corpus had
  nothing, but the 199-record index genuinely holds the answer. These should be
  accepted, and leaving them as \`null\` would train retrieval to stop finding real
  records.

  Tick one box per query. Corpus records: ${local.records.length} local, index adds 199.

  ---

  `;

  writeFileSync(resolve(process.cwd(), "tests/vector-review.md"), header + lines.join("\n"), "utf8");
  console.log(`\n${changed} queries changed by the fallback`);
  console.log("Wrote tests/vector-review.md");

}

void main();
