import { siteUrl } from "@/lib/site-url";
import { SOCIALS, type Network } from "@/lib/social";

import { EMAIL_IMAGES } from "./otp-email-images";
import { OTP } from "./otp-rules";

/**
 * The verification email: subject, HTML and plain text, built from the code
 * alone.
 *
 * Pure — no Resend, no store, nothing read but `siteUrl()` — so
 * `scripts/check-otp.ts` pins it offline, and `deliver()` in `otp.ts` only
 * sends what this returns.
 *
 * It is built the way mail clients need rather than the way the site is:
 * tables and inline styles, because Gmail and Outlook drop most of anything
 * else; PNGs, because neither renders SVG; and alt text on every image, because
 * some clients still block or reject inline images, and the email has to read
 * correctly without them.
 *
 * The images are embedded as inline (CID) attachments rather than loaded from
 * the site: no dependency on a deploy or a public host, and clients that hold
 * remote images until the reader asks still show these, because they are part of
 * the message. `data:` URIs were not an option, because Gmail strips them. The
 * images are generated by `scripts/make-email-assets.ts` into
 * `otp-email-images.ts`. The 440px column sits in an MSO ghost table because
 * desktop Outlook ignores `max-width`. It is kept compact on purpose: the whole
 * message, footer included, fits a laptop Gmail reading pane (about 430px tall)
 * without scrolling. The plain-text part stays for every client that shows no
 * HTML at all.
 *
 * No tracking pixel and no campaign markers on the links: this is the
 * transactional mail someone asked for, not a campaign, and the off-site links
 * stay clean for the reason `email/destinations.ts` gives.
 */

/* The home page's palette, as literals: an email cannot read the site's CSS
   variables. Named after the tokens they copy in globals.css. */
const GROUND = "#2c441e"; // --ground
const CREAM = "#f8a81b"; // --cream
const INK = "#214513"; // --on-cream
const MUTED = "#55703f"; // --field-muted
const CARD = "#ffffff";

const SANS = "Arial, Helvetica, sans-serif";
const SERIF = "Georgia, 'Times New Roman', serif";
const MONO = "'Courier New', Courier, monospace";

/* Both are shown at half their size on disk, so they stay sharp on a dense
   screen (see `scripts/make-email-assets.ts`); the logo's height keeps the
   file's own aspect. */
const LOGO_W = 64;
const LOGO_H = Math.round((LOGO_W * EMAIL_IMAGES.logo.height) / EMAIL_IMAGES.logo.width);
const ICON = 28;

const NAMES: Record<Network, string> = { instagram: "Instagram", youtube: "YouTube", x: "X" };

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export type EmailAttachment = { filename: string; content: string; content_id: string; content_type: string };

const attachment = (img: { filename: string; content: string }, contentId: string): EmailAttachment => ({
  filename: img.filename,
  content: img.content,
  content_id: contentId,
  content_type: "image/png",
});

export function otpEmail(code: string): { subject: string; html: string; text: string; attachments: EmailAttachment[] } {
  const origin = siteUrl();
  // `siteUrl()` only checks the scheme, and a malformed `SITE_URL` must not
  // throw here and fail every send under a misleading "resend call failed" log.
  const host = origin.replace(/^https?:\/\//, "");
  const minutes = OTP.lifeMs / 60_000;
  const span = `${minutes} minute${minutes === 1 ? "" : "s"}`;
  const expiry = `This code expires in ${span}.`;
  const c = esc(code);

  const icons = SOCIALS.map(
    (s) =>
      `<td style="padding:0 5px;"><a href="${esc(s.href)}" target="_blank" style="text-decoration:none;">` +
      `<img src="${esc(`cid:kc-${s.network}`)}" width="${ICON}" height="${ICON}" ` +
      `alt="${esc(NAMES[s.network])}" style="display:block;border:0;width:${ICON}px;height:${ICON}px;` +
      `color:${CREAM};font:12px ${SANS};"></a></td>`,
  ).join("");

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>Your Kranti Cookbook code</title>
</head>
<body style="margin:0;padding:0;background:${GROUND};">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">Your code is ${c}. It expires in ${span}.</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${GROUND}" style="background:${GROUND};">
<tr><td align="center" style="padding:12px;">
<!--[if mso]><table role="presentation" width="440" align="center" cellpadding="0" cellspacing="0" border="0"><tr><td><![endif]-->
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:440px;">
<tr><td align="center" style="padding:0 0 12px;">
<a href="${esc(origin)}" target="_blank" style="text-decoration:none;"><img src="${esc("cid:kc-logo")}" width="${LOGO_W}" height="${LOGO_H}" alt="Kranti Cookbook" style="display:block;border:0;width:${LOGO_W}px;height:auto;color:${CREAM};font:bold 16px ${SERIF};"></a>
</td></tr>
<tr><td bgcolor="${CARD}" style="background:${CARD};border-radius:8px;padding:20px 22px;font-family:${SANS};color:${INK};">
<h1 style="margin:0 0 6px;font:bold 18px/1.3 ${SERIF};color:${INK};">Verify your email</h1>
<p style="margin:0 0 12px;font-size:14px;line-height:1.45;color:${INK};">Enter this code to finish submitting your recipe.</p>
<table role="presentation" align="center" cellpadding="0" cellspacing="0" border="0" style="margin:0 auto 12px;">
<tr><td align="center" style="border:2px solid ${CREAM};border-radius:8px;padding:8px 16px 8px 22px;font:bold 24px/1 ${MONO};letter-spacing:6px;color:${INK};">${c}</td></tr>
</table>
<p style="margin:0 0 2px;font-size:13px;line-height:1.45;color:${INK};">${expiry}</p>
<p style="margin:0 0 8px;font-size:13px;line-height:1.45;color:${INK};">Never share it. Kranti Cookbook will never ask you for it.</p>
<p style="margin:0;font-size:12px;line-height:1.45;color:${MUTED};">Didn&#39;t ask for this? Ignore this email; nothing happens without the code.</p>
</td></tr>
<tr><td align="center" style="padding:14px 0 0;font-family:${SANS};color:${CREAM};">
<p style="margin:0 0 8px;font-size:13px;letter-spacing:0.04em;color:${CREAM};">Follow Kranti Cookbook</p>
<table role="presentation" align="center" cellpadding="0" cellspacing="0" border="0"><tr>${icons}</tr></table>
<p style="margin:10px 0 0;font-size:12px;"><a href="${esc(origin)}" target="_blank" style="color:${CREAM};text-decoration:none;">${esc(host)}</a></p>
</td></tr>
</table>
<!--[if mso]></td></tr></table><![endif]-->
</td></tr>
</table>
</body>
</html>`;

  const text = [
    `Your Kranti Cookbook code is ${code}. ${expiry}`,
    "",
    "Enter it on Kranti Cookbook to finish submitting your recipe. Never share it; Kranti Cookbook will never ask you for it.",
    "",
    "If you did not ask for this, ignore this email.",
    "",
    "Follow Kranti Cookbook:",
    ...SOCIALS.map((s) => `${NAMES[s.network]}: ${s.href}`),
  ].join("\n");

  const attachments = [
    attachment(EMAIL_IMAGES.logo, "kc-logo"),
    ...SOCIALS.map((s) => attachment(EMAIL_IMAGES[s.network], `kc-${s.network}`)),
  ];

  return { subject: `Your Kranti Cookbook code: ${code}`, html, text, attachments };
}
